In [1]:
import pandas as pd

In [2]:
base_casas = pd.read_csv('C:/Users/Jardi/Documents/Cursos/Machine Learning/recursos do curso/Bases de dados/house_prices.csv')

In [3]:
base_casas.shape

(21613, 21)

In [4]:
base_casas

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [5]:
x_casas = base_casas.iloc[:,3:19].values

In [6]:
y_casas = base_casas.iloc[:,2].values

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_casas_treinamento,x_casas_teste,y_casas_treinamento,y_casas_teste=train_test_split(x_casas,y_casas,test_size=0.3)

In [9]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)


In [10]:
x_casas_treinamento_poly=poly.fit_transform(x_casas_treinamento)

In [11]:
x_casas_teste_poly=poly.fit_transform(x_casas_teste)

In [40]:
x_casas_treinamento_poly.shape

(15129, 153)

In [13]:
x_casas_teste_poly.shape

(6484, 153)

In [14]:
x_casas_teste_poly[0]

array([ 1.00000000e+00,  3.00000000e+00,  2.50000000e+00,  1.54000000e+03,
        7.28000000e+03,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        3.00000000e+00,  7.00000000e+00,  1.08000000e+03,  4.60000000e+02,
        1.97400000e+03,  0.00000000e+00,  9.80030000e+04,  4.73102000e+01,
       -1.22322000e+02,  9.00000000e+00,  7.50000000e+00,  4.62000000e+03,
        2.18400000e+04,  3.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        9.00000000e+00,  2.10000000e+01,  3.24000000e+03,  1.38000000e+03,
        5.92200000e+03,  0.00000000e+00,  2.94009000e+05,  1.41930600e+02,
       -3.66966000e+02,  6.25000000e+00,  3.85000000e+03,  1.82000000e+04,
        2.50000000e+00,  0.00000000e+00,  0.00000000e+00,  7.50000000e+00,
        1.75000000e+01,  2.70000000e+03,  1.15000000e+03,  4.93500000e+03,
        0.00000000e+00,  2.45007500e+05,  1.18275500e+02, -3.05805000e+02,
        2.37160000e+06,  1.12112000e+07,  1.54000000e+03,  0.00000000e+00,
        0.00000000e+00,  

In [15]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_casas_treinamento_poly,y_casas_treinamento)

LinearRegression()

In [16]:
previsao=regressor.predict(x_casas_teste_poly)

In [17]:
previsao

array([185380.25014496, 793070.25135803, 440300.10327911, ...,
       364628.0021286 , 267238.99198151, 287583.31678009])

In [18]:
y_casas_teste

array([279000., 846450., 295000., ..., 220650., 261000., 350000.])

In [19]:
from sklearn.metrics import mean_absolute_error
MAE=mean_absolute_error(previsao,y_casas_teste)

In [20]:
from sklearn.metrics import mean_squared_error
MSE=mean_squared_error(previsao,y_casas_teste)

In [21]:
import numpy as np

In [22]:
RMSE=np.sqrt(MSE)

In [23]:
RMSE

165553.31741549194

In [24]:
regressor.score(x_casas_teste_poly,y_casas_teste)

0.8015541576992484